param_namespace:
  # device_url: "serial:///dev/ttyS7:921600"
  device_url: "udp://:14590"
  yaw_offset_correction: -1.5708 # [rad]
  takeoff_height: 1.0 # [m]
  reset_octomap_before_takeoff: true
  waypoint_marker_scale: 0.3
  waypoint_loiter_time: 0.0 # [s]
  waypoint_acceptance_radius: 0.2 # [m]
  mission_timeout_duration: 5.0 # [s]
  control_update_rate: 10.0 # [Hz]
  target_velocity: 1.5 # [m/s]
